-- +goose up

-- Every error this API raises carries one of these SQLSTATE codes, so
-- clients classify by code instead of parsing message text:
--   IRD01  invalid argument  the call itself is malformed
--   IRD02  not defined       the stream, queue, cursor or schedule does not exist
--   IRD03  not found         the message does not exist
-- Why IRD: the natural prefix CB sits in the SQLSTATE class range the
-- standard reserves for itself (0-4, A-H).

CREATE TYPE cb_ref_kind AS ENUM ('message', 'pending');
CREATE TYPE cb_backoff_kind AS ENUM ('none', 'fixed', 'full_jitter');
CREATE TYPE cb_fail_policy AS ENUM ('dead_letter', 'drop');
CREATE TYPE cb_catch_up_policy AS ENUM ('skip', 'all');

-- +goose statementbegin
CREATE FUNCTION cb_valid_name(name text)
RETURNS boolean
LANGUAGE sql IMMUTABLE AS $$
    SELECT name IS NOT NULL
       AND name !~ '__'   -- '__' is reserved, it encodes dots in partition names
       AND name ~ '^[a-z][a-z0-9_]*$'
       AND octet_length(name) <= 20
$$;
-- +goose statementend

-- +goose statementbegin
CREATE FUNCTION _cb_valid_stream_name(name text)
RETURNS boolean
LANGUAGE sql IMMUTABLE AS $$
    SELECT name IS NOT NULL
       AND name ~ '^[a-z][a-z0-9_]*(\.[a-z][a-z0-9_]*){0,2}$'
       AND octet_length(name) <= 44
$$;
-- +goose statementend

-- +goose statementbegin
CREATE FUNCTION _cb_stream_notify(stream text, payload text)
RETURNS void LANGUAGE sql AS $$
    SELECT pg_notify(current_schema || '.cbs_' || stream, payload);
$$;
-- +goose statementend

-- +goose statementbegin
CREATE FUNCTION cb_forever() RETURNS interval LANGUAGE sql IMMUTABLE AS $$
    SELECT interval '-1 second'
$$;
-- +goose statementend

CREATE TABLE cb_streams (
    name text PRIMARY KEY CHECK (_cb_valid_stream_name(name)),
    last_pos bigint NOT NULL DEFAULT 0,
    retention interval NOT NULL DEFAULT cb_forever()
        CHECK (retention = cb_forever() OR retention > interval '0')
);

CREATE TABLE cb_stream_cursors (
    stream text NOT NULL REFERENCES cb_streams(name) ON DELETE CASCADE,
    name text NOT NULL CHECK (cb_valid_name(name)), -- single segment: dots are streams-only
    pos bigint NOT NULL DEFAULT 0, -- how far this cursor has read: everything at or below this position is acked
    PRIMARY KEY (stream, name)
);

-- Messages that are delayed. _cb_stream_deliver_pending moves them
-- into cb_stream_messages when they are due.
CREATE TABLE cb_stream_pending (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    stream text NOT NULL REFERENCES cb_streams(name) ON DELETE CASCADE,
    topic text,
    payload jsonb NOT NULL,
    headers jsonb NOT NULL DEFAULT '{}' CHECK (jsonb_typeof(headers) = 'object'),
    deliver_at timestamptz NOT NULL,
    key text -- set when delayed message has a deduplication key
);

CREATE INDEX ON cb_stream_pending (deliver_at);

CREATE TABLE cb_stream_keys (
    stream text NOT NULL REFERENCES cb_streams(name) ON DELETE CASCADE,
    key            text NOT NULL,
    ref_kind       cb_ref_kind NOT NULL,
    ref_id         bigint NOT NULL,
    ref_created_at timestamptz NOT NULL DEFAULT now(), -- bumped when ref_kind changes from 'pending' to 'message'
    PRIMARY KEY (stream, key)
);

CREATE INDEX ON cb_stream_keys (stream, ref_created_at);

-- No identity column: identity on partitioned tables needs Postgres 17, and
-- the floor is 14 (plan D16). Explicit sequence instead; OWNED BY keeps
-- pg_get_serial_sequence() working in cb_stream_publish.
CREATE SEQUENCE cb_stream_messages_id_seq;

CREATE TABLE cb_stream_messages (
    id bigint NOT NULL DEFAULT nextval('cb_stream_messages_id_seq'),
    stream text NOT NULL REFERENCES cb_streams(name) ON DELETE CASCADE,
    pos bigint,
    topic text,
    payload jsonb NOT NULL,
    headers jsonb NOT NULL DEFAULT '{}' CHECK (jsonb_typeof(headers) = 'object'),
    created_at timestamptz NOT NULL DEFAULT now()
)
PARTITION BY LIST (stream);

ALTER SEQUENCE cb_stream_messages_id_seq OWNED BY cb_stream_messages.id;

CREATE INDEX ON cb_stream_messages (stream, pos);

CREATE TABLE cb_stream_queues (
    stream text NOT NULL REFERENCES cb_streams(name) ON DELETE CASCADE,
    name text NOT NULL CHECK (cb_valid_name(name)),
    claimed_pos bigint NOT NULL DEFAULT 0, -- everything at or below this position is claimed
    closed_pos bigint NOT NULL DEFAULT 0, -- everything at or below this position is claimed and closed
    claim_ttl interval NOT NULL,
    max_attempts int NOT NULL CHECK (max_attempts > 0),
    max_crashes int NOT NULL CHECK (max_crashes > 0),
    backoff_kind cb_backoff_kind NOT NULL,
    backoff_base interval NOT NULL,
    backoff_max interval NOT NULL,
    on_fail cb_fail_policy NOT NULL,
    PRIMARY KEY (stream, name),
    CHECK (closed_pos <= claimed_pos)
);

CREATE TABLE cb_stream_claims (
    stream text NOT NULL,
    queue text NOT NULL,
    from_pos bigint NOT NULL,
    to_pos bigint NOT NULL,
    consumer text NOT NULL,
    closed boolean NOT NULL DEFAULT false,
    ttl interval NOT NULL,
    crashes int NOT NULL DEFAULT 0,
    expires_at timestamptz NOT NULL, -- past this moment any consumer may claim again
    created_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (stream, queue, from_pos),
    FOREIGN KEY (stream, queue)
        REFERENCES cb_stream_queues(stream, name) ON DELETE CASCADE,
    CHECK (from_pos <= to_pos)
);

CREATE TABLE cb_stream_schedules (
    stream   text NOT NULL REFERENCES cb_streams(name) ON DELETE CASCADE,
    name     text NOT NULL CHECK (cb_valid_name(name)),
    every    interval NOT NULL CHECK (
        every > interval '0'
        AND extract(day   FROM every) = 0   -- fixed durations only: no day/month/year
        AND extract(month FROM every) = 0   -- component, so the epoch math in
        AND extract(year  FROM every) = 0   -- _cb_stream_deliver_schedules is exact
    ),
    catch_up cb_catch_up_policy NOT NULL DEFAULT 'skip',
    topic    text,
    payload  jsonb NOT NULL DEFAULT '{}',
    headers  jsonb NOT NULL DEFAULT '{}' CHECK (jsonb_typeof(headers) = 'object'),
    next_at  timestamptz NOT NULL, -- when this schedule fires next
    PRIMARY KEY (stream, name)
);

CREATE INDEX ON cb_stream_schedules (next_at);

-- +goose statementbegin
-- Create the stream's physical partition. Shared by cb_stream_ensure
-- and _cb_stream_ensure.
-- Partition names encode dots as '__'.
CREATE FUNCTION _cb_stream_ensure_partition(stream text)
RETURNS void LANGUAGE plpgsql AS $$
DECLARE
    _partition text := 'cbm__' || replace(_cb_stream_ensure_partition.stream, '.', '__');
BEGIN
    PERFORM pg_advisory_xact_lock(hashtext('cb_stream_ensure'));
    EXECUTE format(
        'CREATE TABLE IF NOT EXISTS %I PARTITION OF cb_stream_messages FOR VALUES IN (%L)',
        _partition, _cb_stream_ensure_partition.stream);
END; $$;
-- +goose statementend

-- +goose statementbegin
-- The internal version accepts the dotted names used by retry and dead letter
-- streams.
CREATE FUNCTION _cb_stream_ensure(stream text, retention interval DEFAULT NULL)
RETURNS void LANGUAGE plpgsql AS $$
BEGIN
    IF NOT _cb_valid_stream_name(_cb_stream_ensure.stream) THEN
        RAISE EXCEPTION 'catbird: invalid stream name %', _cb_stream_ensure.stream USING ERRCODE = 'IRD01';
    END IF;

    INSERT INTO cb_streams (name, retention)
    VALUES (_cb_stream_ensure.stream, coalesce(_cb_stream_ensure.retention, cb_forever()))
    ON CONFLICT DO NOTHING;

    PERFORM _cb_stream_ensure_partition(_cb_stream_ensure.stream);
END; $$;
-- +goose statementend

-- +goose statementbegin
CREATE FUNCTION cb_stream_ensure(stream text, retention interval DEFAULT NULL)
RETURNS void LANGUAGE plpgsql AS $$
BEGIN
    IF NOT cb_valid_name(cb_stream_ensure.stream) THEN
        RAISE EXCEPTION 'catbird: invalid stream name %; use [a-z][a-z0-9_]*, max 20 bytes',
            cb_stream_ensure.stream USING ERRCODE = 'IRD01';
    END IF;

    IF cb_stream_ensure.retention IS NOT NULL
       AND cb_stream_ensure.retention <= interval '0'
       AND cb_stream_ensure.retention <> cb_forever() THEN
        RAISE EXCEPTION 'catbird: retention must be positive, or cb_forever() for no limit (got %)',
            cb_stream_ensure.retention USING ERRCODE = 'IRD01';
    END IF;

    INSERT INTO cb_streams (name, retention)
    VALUES (cb_stream_ensure.stream, coalesce(cb_stream_ensure.retention, cb_forever()))
    ON CONFLICT ON CONSTRAINT cb_streams_pkey DO NOTHING;

    PERFORM _cb_stream_ensure_partition(cb_stream_ensure.stream);
END; $$;
-- +goose statementend

-- +goose statementbegin
CREATE FUNCTION cb_stream_ensure_cursor(stream text, cursor text, start_pos bigint DEFAULT NULL)
RETURNS void LANGUAGE plpgsql AS $$
DECLARE
    _start bigint;
BEGIN
    IF NOT cb_valid_name(cb_stream_ensure_cursor.cursor) THEN
        RAISE EXCEPTION 'catbird: invalid cursor name %; use [a-z][a-z0-9_]*, max 20 bytes',
            cb_stream_ensure_cursor.cursor USING ERRCODE = 'IRD01';
    END IF;

    -- NULL start = tail: skip everything already in the stream.
    SELECT coalesce(cb_stream_ensure_cursor.start_pos, s.last_pos)
    INTO _start FROM cb_streams s WHERE s.name = cb_stream_ensure_cursor.stream;
    IF NOT FOUND THEN
        RAISE EXCEPTION 'catbird: stream % not defined', cb_stream_ensure_cursor.stream USING ERRCODE = 'IRD02';
    END IF;

    INSERT INTO cb_stream_cursors (stream, name, pos)
    VALUES (cb_stream_ensure_cursor.stream, cb_stream_ensure_cursor.cursor, _start)
    ON CONFLICT ON CONSTRAINT cb_stream_cursors_pkey DO NOTHING;
END; $$;
-- +goose statementend

-- +goose statementbegin
CREATE FUNCTION cb_stream_ensure_queue(
    stream         text,
    queue          text,
    start_pos bigint DEFAULT NULL,
    claim_ttl      interval DEFAULT NULL,
    max_attempts   int      DEFAULT NULL,
    backoff_kind   cb_backoff_kind DEFAULT NULL,
    backoff_base   interval DEFAULT NULL,
    backoff_max    interval DEFAULT NULL,
    on_fail        cb_fail_policy DEFAULT NULL,
    max_crashes    int      DEFAULT NULL
)
RETURNS void LANGUAGE plpgsql AS $$
DECLARE
    _start bigint;
BEGIN
    IF NOT cb_valid_name(cb_stream_ensure_queue.queue) THEN
        RAISE EXCEPTION 'catbird: invalid queue name %; use [a-z][a-z0-9_]*, max 20 bytes',
            cb_stream_ensure_queue.queue USING ERRCODE = 'IRD01';
    END IF;

    SELECT coalesce(cb_stream_ensure_queue.start_pos, s.last_pos)
    INTO _start
    FROM cb_streams s
    WHERE s.name = cb_stream_ensure_queue.stream;
    IF NOT FOUND THEN
        RAISE EXCEPTION 'catbird: stream % not defined', cb_stream_ensure_queue.stream USING ERRCODE = 'IRD02';
    END IF;

    INSERT INTO cb_stream_queues
        (stream, name, claimed_pos, closed_pos,
         claim_ttl, max_attempts, max_crashes,
         backoff_kind, backoff_base, backoff_max, on_fail)
    VALUES (
        cb_stream_ensure_queue.stream,
        cb_stream_ensure_queue.queue,
        _start, _start,
        coalesce(cb_stream_ensure_queue.claim_ttl,    interval '30 seconds'),
        coalesce(cb_stream_ensure_queue.max_attempts, 3),
        coalesce(cb_stream_ensure_queue.max_crashes,  3),
        coalesce(cb_stream_ensure_queue.backoff_kind, 'full_jitter'),
        coalesce(cb_stream_ensure_queue.backoff_base, interval '5 seconds'),
        coalesce(cb_stream_ensure_queue.backoff_max,  interval '5 minutes'),
        coalesce(cb_stream_ensure_queue.on_fail,      'dead_letter')
    )
    ON CONFLICT ON CONSTRAINT cb_stream_queues_pkey DO NOTHING;
END; $$;
-- +goose statementend

-- +goose statementbegin
CREATE FUNCTION cb_stream_define_schedule(
    stream   text,
    name     text,
    every    interval,
    topic    text        DEFAULT NULL,
    payload  jsonb       DEFAULT NULL,
    headers  jsonb       DEFAULT NULL,
    catch_up cb_catch_up_policy DEFAULT NULL,
    start_at timestamptz DEFAULT NULL
)
RETURNS void LANGUAGE plpgsql AS $$
DECLARE
    _next_at timestamptz;
BEGIN
    IF NOT cb_valid_name(cb_stream_define_schedule.name) THEN
        RAISE EXCEPTION 'catbird: invalid schedule name %; use [a-z][a-z0-9_]*, max 20 bytes',
            cb_stream_define_schedule.name USING ERRCODE = 'IRD01';
    END IF;

    IF cb_stream_define_schedule.every IS NULL THEN
        RAISE EXCEPTION 'catbird: schedule %.% needs an interval',
            cb_stream_define_schedule.stream, cb_stream_define_schedule.name USING ERRCODE = 'IRD01';
    END IF;

    IF extract(day   FROM cb_stream_define_schedule.every) <> 0
    OR extract(month FROM cb_stream_define_schedule.every) <> 0
    OR extract(year  FROM cb_stream_define_schedule.every) <> 0 THEN
        RAISE EXCEPTION 'catbird: schedule interval must be hours or less (got %); days, months and years need cron',
            cb_stream_define_schedule.every USING ERRCODE = 'IRD01';
    END IF;

    -- cb_ header keys are catbird's own.
    IF cb_stream_define_schedule.headers IS NOT NULL
       AND EXISTS (SELECT 1 FROM jsonb_object_keys(cb_stream_define_schedule.headers) AS k
                   WHERE left(k, 3) = 'cb_') THEN
        RAISE EXCEPTION 'catbird: header keys starting with cb_ are reserved' USING ERRCODE = 'IRD01';
    END IF;

    PERFORM 1 FROM cb_streams s WHERE s.name = cb_stream_define_schedule.stream;
    IF NOT FOUND THEN
        RAISE EXCEPTION 'catbird: stream % not defined', cb_stream_define_schedule.stream USING ERRCODE = 'IRD02';
    END IF;

    -- Topics are never empty; empty means none.
    INSERT INTO cb_stream_schedules AS sc
        (stream, name, every, topic, payload, headers, catch_up, next_at)
    VALUES (
        cb_stream_define_schedule.stream,
        cb_stream_define_schedule.name,
        cb_stream_define_schedule.every,
        nullif(cb_stream_define_schedule.topic, ''),
        coalesce(cb_stream_define_schedule.payload, '{}'),
        coalesce(cb_stream_define_schedule.headers, '{}'),
        coalesce(cb_stream_define_schedule.catch_up, 'skip'),
        coalesce(cb_stream_define_schedule.start_at,
                 clock_timestamp() + cb_stream_define_schedule.every)
    )
    ON CONFLICT ON CONSTRAINT cb_stream_schedules_pkey DO UPDATE
    SET every    = excluded.every,
        topic    = excluded.topic,
        payload  = excluded.payload,
        headers  = excluded.headers,
        catch_up = excluded.catch_up,
        next_at  = CASE
            WHEN cb_stream_define_schedule.start_at IS NOT NULL
                THEN cb_stream_define_schedule.start_at
            WHEN sc.every IS DISTINCT FROM excluded.every
                THEN clock_timestamp() + excluded.every
            ELSE sc.next_at
        END
    -- an identical declaration writes nothing and notifies nothing
    WHERE (sc.every, sc.topic, sc.payload, sc.headers, sc.catch_up)
          IS DISTINCT FROM
          (excluded.every, excluded.topic, excluded.payload, excluded.headers, excluded.catch_up)
       OR cb_stream_define_schedule.start_at IS NOT NULL
    RETURNING sc.next_at INTO _next_at;

    IF _next_at IS NOT NULL THEN
        PERFORM pg_notify(current_schema || '.cb_tick',
            to_char(_next_at AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.US"Z"'));
    END IF;
END; $$;
-- +goose statementend

-- +goose statementbegin
CREATE FUNCTION cb_stream_delete_schedule(stream text, name text)
RETURNS boolean LANGUAGE plpgsql AS $$
DECLARE
    _found boolean;
BEGIN
    DELETE FROM cb_stream_schedules sc
    WHERE sc.stream = cb_stream_delete_schedule.stream
      AND sc.name   = cb_stream_delete_schedule.name
    RETURNING true INTO _found;

    RETURN coalesce(_found, false);
END; $$;
-- +goose statementend

-- +goose statementbegin
CREATE FUNCTION cb_stream_publish(
    stream     text,
    topic      text,
    payload    jsonb,
    headers    jsonb       DEFAULT '{}',
    key        text        DEFAULT NULL,
    delay      interval    DEFAULT NULL,
    deliver_at timestamptz DEFAULT NULL,

    OUT ref_kind cb_ref_kind,
    OUT ref_id   bigint,
    OUT existing boolean
)
LANGUAGE plpgsql AS $$
BEGIN
    -- Header keys starting with cb_ are for catbird's own use.
    IF EXISTS (SELECT 1 FROM jsonb_object_keys(cb_stream_publish.headers) AS k
               WHERE left(k, 3) = 'cb_') THEN
        RAISE EXCEPTION 'catbird: header keys starting with cb_ are reserved' USING ERRCODE = 'IRD01';
    END IF;

    SELECT p.ref_kind, p.ref_id, p.existing INTO ref_kind, ref_id, existing
    FROM _cb_stream_publish(cb_stream_publish.stream, cb_stream_publish.topic,
        cb_stream_publish.payload, cb_stream_publish.headers, cb_stream_publish.key,
        cb_stream_publish.delay, cb_stream_publish.deliver_at) p;
END; $$;
-- +goose statementend

-- +goose statementbegin
-- The internal version allows reserved header keys prefixed with cb_ for use by retry
-- and dead letter streams.
CREATE FUNCTION _cb_stream_publish(
    stream     text,
    topic      text,
    payload    jsonb,
    headers    jsonb       DEFAULT '{}',
    key        text        DEFAULT NULL, -- deduplication key (keep oldest)
    delay      interval    DEFAULT NULL, -- relative delayed delivery
    deliver_at timestamptz DEFAULT NULL, -- absolute delayed delivery

    OUT ref_kind cb_ref_kind,
    OUT ref_id   bigint,
    OUT existing boolean -- true: key already taken, nothing stored
)
LANGUAGE plpgsql AS $$
DECLARE
    _id bigint;
    _deliver_at timestamptz;
    _future boolean;
BEGIN
    existing := false;

    -- Validate arguments.
    IF delay IS NOT NULL AND _cb_stream_publish.deliver_at IS NOT NULL THEN
        RAISE EXCEPTION 'catbird: cannot specify both delay and deliver_at' USING ERRCODE = 'IRD01';
    END IF;

    _deliver_at := coalesce(_cb_stream_publish.deliver_at, clock_timestamp() + _cb_stream_publish.delay);
    _future := _deliver_at IS NOT NULL AND _deliver_at > clock_timestamp();

    -- Check the stream exists.
    PERFORM 1 FROM cb_streams s WHERE s.name = _cb_stream_publish.stream;
    IF NOT FOUND THEN
        RAISE EXCEPTION 'catbird: stream % not defined', _cb_stream_publish.stream USING ERRCODE = 'IRD02';
    END IF;

    ---- Deduplication by key. ----
    IF _cb_stream_publish.key IS NOT NULL THEN
        _id := CASE WHEN _future
            THEN nextval(pg_get_serial_sequence('cb_stream_pending', 'id'))
            ELSE nextval(pg_get_serial_sequence('cb_stream_messages', 'id')) END;

        -- Try to claim this key. If the key is already claimed, learn who owns it.
        -- Do not simplify:
        --   * ON CONFLICT ... DO UPDATE ... WHERE FALSE: on a duplicate key we
        --     must NOT modify the existing row, but plain DO NOTHING would
        --     neither lock it nor let us RETURN it. DO UPDATE locks the
        --     existing row; WHERE FALSE then cancels the update itself.
        --   * RETURNING only produces a row if OUR insert won, so the "won"
        --     CTE is either our new claim or empty.
        --   * The UNION ALL branch reads the existing owner when we lost.
        -- If the competing claim commits while we wait on the conflict, this
        -- statement's snapshot may not see its row yet and both branches come
        -- back empty. The retry SELECT runs as a new statement and handles that race.
        WITH won AS (
            INSERT INTO cb_stream_keys AS k (stream, key, ref_kind, ref_id)
            VALUES (_cb_stream_publish.stream,
                    _cb_stream_publish.key,
                    CASE WHEN _future THEN 'pending' ELSE 'message' END::cb_ref_kind, _id)
            ON CONFLICT ON CONSTRAINT cb_stream_keys_pkey
            DO UPDATE SET ref_id = k.ref_id WHERE FALSE
            RETURNING k.ref_kind, k.ref_id
        )
        SELECT ref.ref_kind, ref.ref_id INTO ref_kind, ref_id FROM (
            SELECT w.ref_kind, w.ref_id FROM won w
            UNION ALL
            SELECT k.ref_kind, k.ref_id FROM cb_stream_keys k
            WHERE k.stream = _cb_stream_publish.stream
              AND k.key         = _cb_stream_publish.key
            LIMIT 1
        ) ref;
        -- Handle race edge case.
        IF ref_id IS NULL THEN
            SELECT k.ref_kind, k.ref_id INTO ref_kind, ref_id
            FROM cb_stream_keys k
            WHERE k.stream = _cb_stream_publish.stream
              AND k.key         = _cb_stream_publish.key;
        END IF;

        -- It's a duplicate. Return the existing id.
        IF ref_id <> _id THEN
            existing := true;
            RETURN;
        END IF;
    END IF;

    ---- Delayed delivery: store as pending, notify the sweeper and return early. ----
    IF _future THEN
        ref_kind := 'pending';
        ref_id   := coalesce(_id, nextval(pg_get_serial_sequence('cb_stream_pending', 'id')));

        INSERT INTO cb_stream_pending
            (id, stream, topic, payload, headers, deliver_at, key)
        VALUES (
            ref_id,
            _cb_stream_publish.stream,
            _cb_stream_publish.topic,
            _cb_stream_publish.payload,
            _cb_stream_publish.headers,
            _deliver_at,
            _cb_stream_publish.key
        );

        PERFORM pg_notify(current_schema || '.cb_tick',
            to_char(_deliver_at AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.US"Z"'));

        RETURN;
    END IF;

    ---- Immediate delivery: store as message, notify the assigner. ----
    ref_kind := 'message';
    ref_id   := coalesce(_id, nextval(pg_get_serial_sequence('cb_stream_messages', 'id')));

    -- id is GENERATED BY DEFAULT, so explicit inserts are allowed.
    INSERT INTO cb_stream_messages (id, stream, topic, payload, headers)
    VALUES (
        ref_id,
        _cb_stream_publish.stream,
        _cb_stream_publish.topic,
        _cb_stream_publish.payload,
        _cb_stream_publish.headers
    );

    -- Notify the position assigner.
    PERFORM _cb_stream_notify(_cb_stream_publish.stream, _cb_stream_publish.topic);
END;
$$;
-- +goose statementend

-- +goose statementbegin
CREATE FUNCTION cb_stream_publish_payloads(stream text, topic text, payloads jsonb[])
RETURNS SETOF bigint LANGUAGE plpgsql AS $$
BEGIN
    PERFORM 1 FROM cb_streams s WHERE s.name = cb_stream_publish_payloads.stream;
    IF NOT FOUND THEN
        RAISE EXCEPTION 'catbird: stream % not defined', cb_stream_publish_payloads.stream USING ERRCODE = 'IRD02';
    END IF;

    RETURN QUERY
    INSERT INTO cb_stream_messages (stream, topic, payload)
    SELECT cb_stream_publish_payloads.stream, cb_stream_publish_payloads.topic, p
    FROM unnest(cb_stream_publish_payloads.payloads) AS p
    RETURNING id;

    PERFORM _cb_stream_notify(cb_stream_publish_payloads.stream, cb_stream_publish_payloads.topic);
END; $$;
-- +goose statementend

-- +goose statementbegin
CREATE FUNCTION _cb_stream_assign_positions(stream text, batch_size int DEFAULT 5000)
RETURNS int
LANGUAGE plpgsql AS $$
DECLARE
    _n int;
BEGIN
    -- Only one process may number a stream at a time.
    IF NOT pg_try_advisory_xact_lock(hashtext('cb_assign:' || _cb_stream_assign_positions.stream)) THEN
        RETURN 0;
    END IF;

    WITH unassigned AS (
        SELECT m.id, row_number() OVER (ORDER BY m.id) AS pos
        FROM cb_stream_messages m
        WHERE m.stream = _cb_stream_assign_positions.stream AND m.pos IS NULL
        ORDER BY m.id
        LIMIT _cb_stream_assign_positions.batch_size
    ), bump AS (
        UPDATE cb_streams s
        SET last_pos = s.last_pos + (SELECT count(*) FROM unassigned)
        WHERE s.name = _cb_stream_assign_positions.stream
        RETURNING s.last_pos - (SELECT count(*) FROM unassigned) AS last_pos
    ), assigned AS (
        UPDATE cb_stream_messages m
        SET pos = bump.last_pos + unassigned.pos
        FROM unassigned, bump
        WHERE m.stream = _cb_stream_assign_positions.stream
          AND m.id = unassigned.id
           -- Not really needed with the advisory lock, just extra safety.
           -- Without the lock, gaps would appear in the position sequence,
           -- but no existing message would be updated.
          AND m.pos IS NULL
        RETURNING 1
    )
    SELECT count(*) INTO _n FROM assigned;

    IF _n > 0 THEN
        -- Inform consumers that new messages are available.
        PERFORM _cb_stream_notify(_cb_stream_assign_positions.stream, '');
    END IF;
    RETURN _n;
END;
$$;
-- +goose statementend

-- +goose statementbegin
CREATE FUNCTION _cb_stream_deliver_pending(batch_size int DEFAULT 500)
RETURNS int LANGUAGE plpgsql AS $$
DECLARE
    _p cb_stream_pending;
    _msg_id bigint;
    _n int := 0;
BEGIN
    FOR _p IN
        SELECT * FROM cb_stream_pending
        WHERE deliver_at <= clock_timestamp()
        ORDER BY deliver_at LIMIT _cb_stream_deliver_pending.batch_size
        FOR UPDATE SKIP LOCKED
    LOOP
        DELETE FROM cb_stream_pending WHERE id = _p.id;

        -- Publish the message
        INSERT INTO cb_stream_messages (stream, topic, payload, headers)
        VALUES (_p.stream, _p.topic, _p.payload, _p.headers)
        RETURNING id INTO _msg_id;
        -- If the message has a key, update it.
        UPDATE cb_stream_keys k
        SET ref_kind = 'message', ref_id = _msg_id, ref_created_at = now()
        WHERE k.ref_kind = 'pending' AND k.ref_id = _p.id AND k.stream = _p.stream;

        PERFORM _cb_stream_notify(_p.stream, _p.topic);

        _n := _n + 1;
    END LOOP;
    RETURN _n;
END;
$$;
-- +goose statementend

-- +goose statementbegin
CREATE FUNCTION _cb_stream_deliver_schedules(batch_size int DEFAULT 500)
RETURNS int LANGUAGE plpgsql AS $$
DECLARE
    _schedule cb_stream_schedules;
    _due_ticks int;  -- ticks due from next_at through now, inclusive (always >= 1)
    _fire_ticks int; -- how many of those ticks this policy actually emits
    _n int := 0;     -- messages published, the return value (matches _cb_stream_deliver_pending)
BEGIN
    FOR _schedule IN
        SELECT * FROM cb_stream_schedules
        WHERE next_at <= clock_timestamp()
        ORDER BY next_at LIMIT _cb_stream_deliver_schedules.batch_size
        FOR UPDATE SKIP LOCKED
    LOOP
        -- Ticks due from next_at through now -- at least one, since the row is due.
        _due_ticks := floor(extract(epoch FROM clock_timestamp() - _schedule.next_at)
            / extract(epoch FROM _schedule.every))::int + 1;

        -- 'all' replays every missed tick. 'skip' fires only an on-time tick
        -- (_due_ticks = 1) and skips the backlog (_due_ticks > 1).
        _fire_ticks := CASE WHEN _schedule.catch_up = 'all' THEN _due_ticks
                            WHEN _due_ticks = 1             THEN 1
                            ELSE 0 END;

        IF _fire_ticks > 0 THEN
            INSERT INTO cb_stream_messages (stream, topic, payload, headers)
            SELECT _schedule.stream, _schedule.topic, _schedule.payload, _schedule.headers
            FROM generate_series(1, _fire_ticks);

            PERFORM _cb_stream_notify(_schedule.stream, _schedule.topic);

            _n := _n + _fire_ticks;
        END IF;

        -- Re-arm to the first tick after now, in one step. Same expression for
        -- both policies: 'all' has just caught up to it, 'skip' jumps its
        -- backlog past it. Anchored on the old next_at, so tick phase holds.
        UPDATE cb_stream_schedules sc
        SET next_at = _schedule.next_at + _schedule.every * _due_ticks
        WHERE sc.stream = _schedule.stream
          AND sc.name = _schedule.name;
    END LOOP;

    RETURN _n;
END;
$$;
-- +goose statementend

-- +goose statementbegin
CREATE FUNCTION _cb_stream_prune_messages(stream text, batch_size int DEFAULT 10000)
RETURNS bigint LANGUAGE plpgsql AS $$
DECLARE
    _retention interval;
    _n bigint;
BEGIN
    SELECT s.retention INTO _retention
    FROM cb_streams s WHERE s.name = _cb_stream_prune_messages.stream;
    IF NOT FOUND THEN
        RAISE EXCEPTION 'catbird: stream % not defined', _cb_stream_prune_messages.stream USING ERRCODE = 'IRD02';
    END IF;
    IF _retention < interval '0' THEN  -- cb_forever() sentinel: nothing to prune
        RETURN 0;
    END IF;

    WITH doomed AS (
        SELECT m.ctid FROM cb_stream_messages m
        WHERE m.stream = _cb_stream_prune_messages.stream
          AND m.created_at < clock_timestamp() - _retention
        ORDER BY m.pos
        LIMIT _cb_stream_prune_messages.batch_size
        FOR UPDATE SKIP LOCKED
    )
    DELETE FROM cb_stream_messages m USING doomed d
    WHERE m.stream = _cb_stream_prune_messages.stream
      AND m.ctid = d.ctid;

    GET DIAGNOSTICS _n = ROW_COUNT;
    RETURN _n;
END; $$;
-- +goose statementend

-- +goose statementbegin
CREATE FUNCTION _cb_stream_prune_keys(stream text, batch_size int DEFAULT 10000)
RETURNS bigint LANGUAGE plpgsql AS $$
DECLARE
    _retention interval;
    _n bigint;
BEGIN
    SELECT s.retention INTO _retention
    FROM cb_streams s WHERE s.name = _cb_stream_prune_keys.stream;
    IF NOT FOUND THEN
        RAISE EXCEPTION 'catbird: stream % not defined', _cb_stream_prune_keys.stream USING ERRCODE = 'IRD02';
    END IF;
    IF _retention < interval '0' THEN  -- cb_forever() sentinel: nothing to prune
        RETURN 0;
    END IF;

    WITH doomed AS (
        SELECT k.ctid FROM cb_stream_keys k
        WHERE k.stream = _cb_stream_prune_keys.stream
          AND k.ref_kind = 'message'  -- keep undelivered 'pending' keys
          AND k.ref_created_at < clock_timestamp() - _retention
        ORDER BY k.ref_created_at
        LIMIT _cb_stream_prune_keys.batch_size
        FOR UPDATE SKIP LOCKED
    )
    DELETE FROM cb_stream_keys k USING doomed d
    WHERE k.ctid = d.ctid;

    GET DIAGNOSTICS _n = ROW_COUNT;
    RETURN _n;
END; $$;
-- +goose statementend

-- +goose statementbegin
CREATE FUNCTION cb_stream_read(stream text, cursor text, batch_size int DEFAULT 100)
RETURNS SETOF cb_stream_messages
LANGUAGE plpgsql AS $$
DECLARE
    _pos bigint;
    _new_pos bigint;
BEGIN
    -- Get current cursor position.
    SELECT c.pos INTO _pos FROM cb_stream_cursors c
    WHERE c.stream = cb_stream_read.stream AND c.name = cb_stream_read.cursor
    FOR UPDATE;

    IF NOT FOUND THEN
        RAISE EXCEPTION 'catbird: cursor %.% not defined', cb_stream_read.stream, cb_stream_read.cursor USING ERRCODE = 'IRD02';
    END IF;

    SELECT max(b.pos) INTO _new_pos FROM (
        SELECT m.pos FROM cb_stream_messages m
        WHERE m.stream = cb_stream_read.stream
          AND m.pos > _pos
        ORDER BY m.pos
        LIMIT cb_stream_read.batch_size) b;

    IF _new_pos IS NULL THEN
        RETURN;
    END IF;

    RETURN QUERY
    SELECT m.* FROM cb_stream_messages m
    WHERE m.stream = cb_stream_read.stream
      AND m.pos > _pos AND m.pos <= _new_pos
    ORDER BY m.pos;

    UPDATE cb_stream_cursors c SET pos = _new_pos
    WHERE c.stream = cb_stream_read.stream AND c.name = cb_stream_read.cursor;
END; $$;
-- +goose statementend

-- +goose statementbegin
-- Move the closed position forward over adjacent closed claims until an
-- open claim stops it.
CREATE FUNCTION _cb_stream_advance_closed_position(stream text, queue text)
RETURNS void LANGUAGE plpgsql AS $$
DECLARE
    _closed_pos bigint;
    _to_pos bigint;
BEGIN
    SELECT q.closed_pos INTO _closed_pos FROM cb_stream_queues q
    WHERE q.stream = _cb_stream_advance_closed_position.stream
      AND q.name = _cb_stream_advance_closed_position.queue
    FOR UPDATE;

    LOOP
        DELETE FROM cb_stream_claims c
        WHERE c.stream   = _cb_stream_advance_closed_position.stream
          AND c.queue    = _cb_stream_advance_closed_position.queue
          AND c.from_pos = _closed_pos + 1
          AND c.closed
        RETURNING c.to_pos INTO _to_pos;
        EXIT WHEN NOT FOUND;
        _closed_pos := _to_pos;
    END LOOP;

    UPDATE cb_stream_queues q SET closed_pos = _closed_pos
    WHERE q.stream = _cb_stream_advance_closed_position.stream
      AND q.name = _cb_stream_advance_closed_position.queue
      AND q.closed_pos < _closed_pos;
END; $$;
-- +goose statementend

-- +goose statementbegin
-- Rules every branch of this function must preserve (checkClaims in the Go
-- test suite checks them after every step):
--   1. Open and closed claims exactly cover the region between closed_pos
--      and claimed_pos. No gaps, no overlaps. Whoever removes or splits a
--      claim must leave the tiling intact, or the closed position stalls
--      and messages are lost to retention.
--   2. claimed_pos and closed_pos only ever grow.
--   3. Dead-letter a message only when it is proven to be the problem.
--      The proof is a crash count above max_crashes: whole ranges stop
--      being handed out once they reach the limit, so a count can only
--      get above it when a message crashes while alone in its claim.
CREATE FUNCTION cb_stream_claim(
    stream     text,
    queue      text,
    consumer   text,
    batch_size int      DEFAULT 100,
    ttl        interval DEFAULT NULL, -- the queue's claim_ttl is used if NULL

    OUT from_pos   bigint, -- NULL when there is nothing to claim
    OUT to_pos     bigint,
    OUT expires_at timestamptz
)
LANGUAGE plpgsql AS $$
DECLARE
    _ttl interval;
    _max_crashes int;
    _c cb_stream_claims;
    _claimed_pos bigint;
    _last_pos bigint;
BEGIN
    SELECT coalesce(cb_stream_claim.ttl, q.claim_ttl), q.max_crashes
    INTO _ttl, _max_crashes FROM cb_stream_queues q
    WHERE q.stream = cb_stream_claim.stream AND q.name = cb_stream_claim.queue;
    IF NOT FOUND THEN
        RAISE EXCEPTION 'catbird: queue %.% not defined', cb_stream_claim.stream, cb_stream_claim.queue USING ERRCODE = 'IRD02';
    END IF;

    ---- Try to adopt an expired claim. ----
    -- A range that keeps expiring is suspected of crashing its consumers.
    -- At max_crashes the range is no longer handed out whole. It is split
    -- so each message gets one solo attempt, Messages that still crash
    -- are added to the dead letter queue. The other messages close normally.
    LOOP
        SELECT r.* INTO _c
        FROM cb_stream_claims r
        WHERE r.stream = cb_stream_claim.stream
          AND r.queue  = cb_stream_claim.queue
          AND NOT r.closed
          AND r.expires_at <= clock_timestamp()
        ORDER BY r.from_pos
        LIMIT 1
        FOR UPDATE SKIP LOCKED;
        EXIT WHEN NOT FOUND; -- nothing expired, claim a fresh range

        IF _c.from_pos = _c.to_pos AND _c.crashes > _max_crashes THEN
            -- A solo message whose count is above the limit has crashed.
            -- This is a problematic message. Add to the dead letter queue
            -- and close the claim.
            PERFORM _cb_stream_dead_letter(cb_stream_claim.stream, cb_stream_claim.queue,
                _c.from_pos, _c.crashes, 'crash limit reached');

            UPDATE cb_stream_claims c
            SET closed = true
            WHERE (c.stream, c.queue, c.from_pos)
                = (_c.stream, _c.queue, _c.from_pos);

            PERFORM _cb_stream_advance_closed_position(cb_stream_claim.stream, cb_stream_claim.queue);

        ELSIF _c.from_pos < _c.to_pos AND _c.crashes >= _max_crashes THEN
            -- This range crashed too often, and nobody knows which message
            -- is to blame. So from here on, its messages are handed out one
            -- at a time. The caller gets the first message. The rest
            -- becomes a new claim that is already expired, so the next
            -- caller picks it up and lands here again.
            UPDATE cb_stream_claims c
            SET to_pos = _c.from_pos,
                consumer    = cb_stream_claim.consumer,
                ttl         = coalesce(cb_stream_claim.ttl, c.ttl),
                expires_at  = clock_timestamp() + coalesce(cb_stream_claim.ttl, c.ttl),
                crashes     = c.crashes + 1
            WHERE (c.stream, c.queue, c.from_pos)
                = (_c.stream, _c.queue, _c.from_pos)
            RETURNING c.from_pos, c.to_pos, c.expires_at
            INTO from_pos, to_pos, expires_at;

            INSERT INTO cb_stream_claims
                (stream, queue, from_pos, to_pos, consumer,
                 ttl, expires_at, crashes)
            VALUES (_c.stream, _c.queue, _c.from_pos + 1, _c.to_pos,
                _c.consumer, _c.ttl, clock_timestamp(), _c.crashes);
            RETURN;
        ELSE
            -- Hand out the whole range with a fresh deadline. Two cases
            -- land here: a range still below the crash limit, handed out
            -- again as is, or a solo message at the limit, handed
            -- out one last time. If it crashes now, it crashed alone,
            -- its count passes the limit, and the branch above removes it.
            UPDATE cb_stream_claims c
            SET consumer   = cb_stream_claim.consumer,
                ttl        = coalesce(cb_stream_claim.ttl, c.ttl),
                expires_at = clock_timestamp() + coalesce(cb_stream_claim.ttl, c.ttl),
                crashes    = c.crashes + 1
            WHERE (c.stream, c.queue, c.from_pos)
                = (_c.stream, _c.queue, _c.from_pos)
            RETURNING c.from_pos, c.to_pos, c.expires_at
            INTO from_pos, to_pos, expires_at;
            RETURN;
        END IF;
    END LOOP;

    ---- Claim a fresh range. ----
    SELECT q.claimed_pos INTO _claimed_pos
    FROM cb_stream_queues q
    WHERE q.stream = cb_stream_claim.stream AND q.name = cb_stream_claim.queue
    FOR UPDATE;

    -- No lock needed on the streams row. last_position only grows,
    -- so a stale read just means a slightly smaller range.
    SELECT s.last_pos INTO _last_pos FROM cb_streams s
    WHERE s.name = cb_stream_claim.stream;

    IF _claimed_pos >= _last_pos THEN
        RETURN; -- caught up, return NULLs
    END IF;

    from_pos := _claimed_pos + 1;
    to_pos := least(_claimed_pos + cb_stream_claim.batch_size, _last_pos);
    expires_at := clock_timestamp() + _ttl;

    UPDATE cb_stream_queues q
    SET claimed_pos = cb_stream_claim.to_pos
    WHERE q.stream = cb_stream_claim.stream
      AND q.name = cb_stream_claim.queue;

    INSERT INTO cb_stream_claims
        (stream, queue, from_pos, to_pos, consumer, ttl, expires_at, crashes)
    VALUES (
        cb_stream_claim.stream,
        cb_stream_claim.queue,
        cb_stream_claim.from_pos,
        cb_stream_claim.to_pos,
        cb_stream_claim.consumer,
        _ttl,
        cb_stream_claim.expires_at,
        0
    );
END;
$$;
-- +goose statementend

-- +goose statementbegin
-- If ttl is NULL, the claim's existing ttl is used. Returns the new expires_at timestamp.
CREATE FUNCTION cb_stream_extend_claim(
    stream text, queue text,
    consumer text,
    from_pos bigint,
    ttl interval DEFAULT NULL
)
RETURNS timestamptz LANGUAGE plpgsql AS $$
DECLARE
    _expires_at timestamptz;
BEGIN
    IF cb_stream_extend_claim.ttl <= '0' THEN
        RAISE EXCEPTION 'catbird: invalid ttl %', cb_stream_extend_claim.ttl USING ERRCODE = 'IRD01';
    END IF;

    UPDATE cb_stream_claims c
    SET expires_at = clock_timestamp() + coalesce(cb_stream_extend_claim.ttl, c.ttl)
    WHERE c.stream   = cb_stream_extend_claim.stream
      AND c.queue    = cb_stream_extend_claim.queue
      AND c.consumer      = cb_stream_extend_claim.consumer
      AND c.from_pos = cb_stream_extend_claim.from_pos
      AND NOT c.closed
    RETURNING c.expires_at INTO _expires_at;
    RETURN _expires_at;
END; $$;
-- +goose statementend

-- +goose statementbegin
-- the claim expires immediately, and the next cb_stream_claim call may adopt it.
CREATE FUNCTION cb_stream_release_claim(
    stream text,
    queue text,
    consumer text,
    from_pos bigint
)
RETURNS void LANGUAGE plpgsql AS $$
BEGIN
    UPDATE cb_stream_claims c
    SET expires_at = clock_timestamp()
    WHERE c.stream   = cb_stream_release_claim.stream
      AND c.queue    = cb_stream_release_claim.queue
      AND c.consumer      = cb_stream_release_claim.consumer
      AND c.from_pos = cb_stream_release_claim.from_pos
      AND NOT c.closed;
END; $$;
-- +goose statementend

-- +goose statementbegin
CREATE FUNCTION cb_stream_close_claim(
    stream text,
    queue text,
    consumer text,
    from_pos bigint
)
RETURNS void LANGUAGE plpgsql AS $$
BEGIN
    -- Only the current owner may close.
    UPDATE cb_stream_claims c SET closed = true
    WHERE c.stream   = cb_stream_close_claim.stream
      AND c.queue    = cb_stream_close_claim.queue
      AND c.consumer = cb_stream_close_claim.consumer
      AND c.from_pos = cb_stream_close_claim.from_pos
      AND NOT c.closed;
    IF NOT FOUND THEN
        RETURN;
    END IF;

    PERFORM _cb_stream_advance_closed_position(cb_stream_close_claim.stream, cb_stream_close_claim.queue);
END; $$;
-- +goose statementend

-- +goose statementbegin
CREATE FUNCTION _cb_backoff(kind cb_backoff_kind, base_delay interval, max_delay interval, attempt int)
RETURNS interval LANGUAGE plpgsql AS $$
DECLARE
    _cap interval;
BEGIN
    CASE _cb_backoff.kind
    WHEN 'none' THEN
        RETURN '0';
    WHEN 'fixed' THEN
        RETURN least(_cb_backoff.base_delay, _cb_backoff.max_delay);
    WHEN 'full_jitter' THEN
        _cap := least(_cb_backoff.base_delay * (2 ^ least(_cb_backoff.attempt - 1, 20)),
                      _cb_backoff.max_delay);
        RETURN _cap * random();
    ELSE
        RAISE EXCEPTION 'catbird: unknown backoff kind %', _cb_backoff.kind USING ERRCODE = 'IRD01';
    END CASE;
END; $$;
-- +goose statementend

-- +goose statementbegin
-- Publish a message to the stream's dead letter queue (sd.<base>).
-- Silently does nothing when retention already dropped the
-- message. The deduplication key collapses duplicate
-- reports of the same failure.
CREATE FUNCTION _cb_stream_dead_letter(
    stream text,
    queue text,
    pos bigint, -- 'position' is a keyword: legal for columns, not parameters
    attempts int,
    error text
)
RETURNS void LANGUAGE plpgsql AS $$
DECLARE
    _m cb_stream_messages;
    _base_name text;
    _origin_pos bigint;
BEGIN
    SELECT m.* INTO _m FROM cb_stream_messages m
    WHERE m.stream = _cb_stream_dead_letter.stream
      AND m.pos    = _cb_stream_dead_letter.pos;
    IF NOT FOUND THEN
        RETURN;
    END IF;

    _base_name := CASE WHEN _cb_stream_dead_letter.stream LIKE '%.%'
                  THEN split_part(_cb_stream_dead_letter.stream, '.', 2)
                  ELSE _cb_stream_dead_letter.stream END;

    _origin_pos := coalesce((_m.headers->>'cb_origin_pos')::bigint,
        _cb_stream_dead_letter.pos);

    PERFORM _cb_stream_ensure('sd.' || _base_name);
    PERFORM _cb_stream_publish(
        'sd.' || _base_name,
        _m.topic,
        _m.payload,
        headers => _m.headers || jsonb_build_object(
            'cb_origin_pos', _origin_pos,
            'cb_queue',    _cb_stream_dead_letter.queue,
            'cb_attempts', _cb_stream_dead_letter.attempts,
            'cb_error',    _cb_stream_dead_letter.error),
        key => _cb_stream_dead_letter.queue || ':' || _origin_pos || ':dead_letter');
END; $$;
-- +goose statementend

-- +goose statementbegin
-- Called once per message a handler could not process. It republishes the message
-- to the queue's retry stream with a backoff delay while attempts remain or to the
-- dead letter queue when they are used up. The claim closes normally.
CREATE FUNCTION cb_stream_fail(stream text, queue text, pos bigint, error text)
RETURNS void LANGUAGE plpgsql AS $$
DECLARE
    _m cb_stream_messages;
    _q cb_stream_queues;
    _base_name text;
    _retry_stream text;
    _attempt int;
    _origin_pos bigint;
BEGIN
    SELECT m.* INTO _m FROM cb_stream_messages m
    WHERE m.stream = cb_stream_fail.stream AND m.pos = cb_stream_fail.pos;
    IF NOT FOUND THEN
        RAISE EXCEPTION 'catbird: message %.% not found',
            cb_stream_fail.stream, cb_stream_fail.pos USING ERRCODE = 'IRD03';
    END IF;

    _base_name := CASE WHEN cb_stream_fail.stream LIKE '%.%'
                  THEN split_part(cb_stream_fail.stream, '.', 2)
                  ELSE cb_stream_fail.stream END;

    SELECT q.* INTO _q FROM cb_stream_queues q
    WHERE q.stream = _base_name AND q.name = cb_stream_fail.queue;
    IF NOT FOUND THEN
        RAISE EXCEPTION 'catbird: queue %.% not defined', _base_name, cb_stream_fail.queue USING ERRCODE = 'IRD02';
    END IF;

    _attempt := coalesce((_m.headers->>'cb_attempt')::int, 0) + 1;
    _origin_pos := coalesce((_m.headers->>'cb_origin_pos')::bigint, cb_stream_fail.pos);

    IF _attempt >= _q.max_attempts THEN
        IF _q.on_fail = 'dead_letter' THEN
            PERFORM _cb_stream_dead_letter(cb_stream_fail.stream, cb_stream_fail.queue,
                cb_stream_fail.pos, _attempt, cb_stream_fail.error);
        END IF;
        RETURN;
    END IF;

    _retry_stream := 'sr.' || _base_name || '.' || cb_stream_fail.queue;

    -- retry messages are handled history: keep a bounded window, not forever
    PERFORM _cb_stream_ensure(_retry_stream, interval '7 days');
    PERFORM cb_stream_ensure_queue(_retry_stream, cb_stream_fail.queue, 0);

    PERFORM _cb_stream_publish(
        _retry_stream,
        _m.topic,
        _m.payload,
        key => cb_stream_fail.queue || ':' || _origin_pos || ':' || _attempt,
        headers => _m.headers || jsonb_build_object(
            'cb_attempt',         _attempt,
            'cb_origin_pos', _origin_pos,
            'cb_error',           cb_stream_fail.error),
        delay => _cb_backoff(_q.backoff_kind, _q.backoff_base, _q.backoff_max, _attempt));
END; $$;
-- +goose statementend

-- +goose down

DROP FUNCTION _cb_stream_deliver_schedules(int);
DROP FUNCTION _cb_stream_prune_messages(text, int);
DROP FUNCTION _cb_stream_prune_keys(text, int);
DROP FUNCTION cb_stream_delete_schedule(text, text);
DROP FUNCTION cb_stream_define_schedule(text, text, interval, text, jsonb, jsonb, cb_catch_up_policy, timestamptz);
DROP TABLE cb_stream_schedules;
DROP TYPE cb_catch_up_policy;

DROP FUNCTION cb_stream_fail(text, text, bigint, text);
DROP FUNCTION _cb_stream_dead_letter(text, text, bigint, int, text);
DROP FUNCTION _cb_backoff(cb_backoff_kind, interval, interval, int);
DROP FUNCTION cb_stream_close_claim(text, text, text, bigint);
DROP FUNCTION _cb_stream_advance_closed_position(text, text);
DROP FUNCTION cb_stream_release_claim(text, text, text, bigint);
DROP FUNCTION cb_stream_extend_claim(text, text, text, bigint, interval);
DROP FUNCTION cb_stream_claim(text, text, text, int, interval);
DROP FUNCTION cb_stream_ensure_queue(text, text, bigint, interval, int, cb_backoff_kind, interval, interval, cb_fail_policy, int);
DROP FUNCTION cb_stream_ensure_cursor(text, text, bigint);
DROP FUNCTION cb_stream_read(text, text, int);
DROP TABLE cb_stream_claims;
DROP TABLE cb_stream_queues;
DROP FUNCTION cb_stream_publish_payloads(text, text, jsonb[]);
DROP FUNCTION cb_stream_publish(text, text, jsonb, jsonb, text, interval, timestamptz);
DROP FUNCTION _cb_stream_publish(text, text, jsonb, jsonb, text, interval, timestamptz);
DROP FUNCTION cb_stream_ensure(text, interval);
DROP FUNCTION _cb_stream_ensure(text, interval);
DROP FUNCTION _cb_stream_ensure_partition(text);
DROP FUNCTION _cb_stream_deliver_pending(int);
DROP FUNCTION _cb_stream_assign_positions(text, int);
DROP FUNCTION _cb_stream_notify(text, text);
DROP TABLE cb_stream_messages;
DROP TABLE cb_stream_cursors;
DROP TABLE cb_stream_keys;
DROP TABLE cb_stream_pending;
DROP TABLE cb_streams;
DROP FUNCTION cb_forever(); -- after cb_streams: its default and CHECK depend on it
DROP FUNCTION _cb_valid_stream_name(text);
DROP FUNCTION cb_valid_name(text);
DROP TYPE cb_ref_kind;
DROP TYPE cb_backoff_kind;
DROP TYPE cb_fail_policy;
