-- +goose up

CREATE TYPE cb_ref_kind AS ENUM ('message', 'pending');

-- +goose statementbegin
CREATE FUNCTION cb_valid_name(name text)
RETURNS boolean
LANGUAGE sql IMMUTABLE AS $$
    SELECT name IS NOT NULL
       AND name ~ '^[a-z][a-z0-9_]*$'
       AND octet_length(name) <= 32
$$;
-- +goose statementend

-- +goose statementbegin
CREATE FUNCTION _cb_valid_stream_name(name text)
RETURNS boolean
LANGUAGE sql IMMUTABLE AS $$
    SELECT name IS NOT NULL
       AND name ~ '^[a-z][a-z0-9_]*(\.[a-z][a-z0-9_]*){0,2}$'
       AND octet_length(name) <= 32
$$;
-- +goose statementend

CREATE TABLE cb_streams (
    name text PRIMARY KEY CHECK (_cb_valid_stream_name(name)),
    last_position bigint NOT NULL DEFAULT 0
);

CREATE TABLE cb_stream_cursors (
    stream_name text NOT NULL REFERENCES cb_streams(name) ON DELETE CASCADE,
    name text NOT NULL CHECK (cb_valid_name(name)), -- single segment: dots are streams-only
    position bigint NOT NULL DEFAULT 0, -- how far this cursor has read: everything at or below this position is acked
    PRIMARY KEY (stream_name, name)
);

-- Messages that are waiting. The sweeper moves them into cb_stream_messages
-- when they are due. There are 2 kinds: delayed publish and retries.
CREATE TABLE cb_stream_pending (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    stream_name text NOT NULL REFERENCES cb_streams(name) ON DELETE CASCADE,
    topic text,
    payload jsonb NOT NULL,
    headers jsonb NOT NULL DEFAULT '{}' CHECK (jsonb_typeof(headers) = 'object'),
    deliver_at timestamptz NOT NULL,
    key text, -- set when delayed message has a deduplication key
    group_name text,  -- set for retries
    attempt int, -- set for retries
    original_position bigint, -- set for retries
    CHECK (num_nulls(group_name, attempt, original_position) IN (0, 3))
);

CREATE INDEX ON cb_stream_pending (deliver_at);

CREATE UNIQUE INDEX ON cb_stream_pending (stream_name, group_name, original_position)
WHERE original_position IS NOT NULL;

CREATE TABLE cb_stream_keys (
    stream_name text NOT NULL REFERENCES cb_streams(name) ON DELETE CASCADE,
    key         text NOT NULL,
    ref_kind    cb_ref_kind NOT NULL,
    ref_id      bigint NOT NULL,
    created_at  timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (stream_name, key)
);

CREATE INDEX ON cb_stream_keys (stream_name, created_at);

-- No identity column: identity on partitioned tables needs Postgres 17, and
-- the floor is 14 (plan D16). Explicit sequence instead; OWNED BY keeps
-- pg_get_serial_sequence() working in cb_stream_publish.
CREATE SEQUENCE cb_stream_messages_id_seq;

CREATE TABLE cb_stream_messages (
    id bigint NOT NULL DEFAULT nextval('cb_stream_messages_id_seq'),
    stream_name text NOT NULL REFERENCES cb_streams(name) ON DELETE CASCADE,
    position bigint,
    topic text,
    payload jsonb NOT NULL,
    headers jsonb NOT NULL DEFAULT '{}' CHECK (jsonb_typeof(headers) = 'object'),
    created_at timestamptz NOT NULL DEFAULT now()
)
PARTITION BY LIST (stream_name);

ALTER SEQUENCE cb_stream_messages_id_seq OWNED BY cb_stream_messages.id;

CREATE INDEX ON cb_stream_messages (stream_name, position);

-- +goose statementbegin
CREATE FUNCTION cb_stream_ensure(stream text)
RETURNS void LANGUAGE plpgsql AS $$
BEGIN
    IF NOT cb_valid_name(cb_stream_ensure.stream) THEN
        RAISE EXCEPTION 'catbird: invalid stream name %; use [a-z][a-z0-9_]*, max 32 bytes', cb_stream_ensure.stream;
    END IF;
    PERFORM pg_advisory_xact_lock(hashtext('cb_stream_ensure'));
    INSERT INTO cb_streams (name) VALUES (cb_stream_ensure.stream) ON CONFLICT DO NOTHING;
    EXECUTE format(
        'CREATE TABLE IF NOT EXISTS %I PARTITION OF cb_stream_messages
         FOR VALUES IN (%L) PARTITION BY RANGE (created_at)',
        'cb_stream_messages__' || cb_stream_ensure.stream, cb_stream_ensure.stream);
    EXECUTE format( -- TODO temporary
        'CREATE TABLE IF NOT EXISTS %I PARTITION OF %I
         FOR VALUES FROM (%L) TO (%L)',
        format('cb_stream_messages__%s__dev', cb_stream_ensure.stream),
        'cb_stream_messages__' || cb_stream_ensure.stream, '2000-01-01', '2100-01-01');
END; $$;
-- +goose statementend

-- +goose statementbegin
CREATE FUNCTION cb_stream_publish(
    stream     text,
    topic      text,
    payload    jsonb,
    headers    jsonb       DEFAULT '{}',
    key        text        DEFAULT NULL, -- deduplication key (keep oldest)
    delay      interval    DEFAULT NULL, -- relative delayed delivery
    deliver_at timestamptz DEFAULT NULL, -- absolute delayed delivery

    OUT ref_kind cb_ref_kind,
    OUT ref_id   bigint,
    OUT existing boolean -- true: key already taken, nothing stored
)
LANGUAGE plpgsql AS $$
-- Resolve ambiguous names to COLUMNS inside SQL statements: the parameter
-- `key` collides with cb_stream_keys.key in the ON CONFLICT target, which
-- cannot be table-qualified. Safe because parameters are always referenced
-- qualified (cb_stream_publish.key) in this body.
#variable_conflict use_column
DECLARE
    _id bigint;
    _deliver_at timestamptz;
    _future boolean;
BEGIN
    existing := false;

    -- Validate arguments.
    IF delay IS NOT NULL AND cb_stream_publish.deliver_at IS NOT NULL THEN
        RAISE EXCEPTION 'catbird: cannot specify both delay and deliver_at';
    END IF;

    _deliver_at := coalesce(cb_stream_publish.deliver_at, clock_timestamp() + cb_stream_publish.delay);
    _future := _deliver_at IS NOT NULL AND _deliver_at > clock_timestamp();

    -- Check the stream exists.
    PERFORM 1 FROM cb_streams s WHERE s.name = cb_stream_publish.stream;
    IF NOT FOUND THEN
        RAISE EXCEPTION 'catbird: stream % not defined', cb_stream_publish.stream;
    END IF;

    ---- Deduplication by key. ----
    IF cb_stream_publish.key IS NOT NULL THEN
        _id := CASE WHEN _future
            THEN nextval(pg_get_serial_sequence('cb_stream_pending', 'id'))
            ELSE nextval(pg_get_serial_sequence('cb_stream_messages', 'id')) END;

        -- Try to claim this key. If the key is already claimed, learn who owns it.
        -- Do not simplify:
        --   * ON CONFLICT ... DO UPDATE ... WHERE FALSE: on a duplicate key we
        --     must NOT modify the existing row, but plain DO NOTHING would
        --     neither lock it nor let us RETURN it. DO UPDATE locks the
        --     existing row; WHERE FALSE then cancels the update itself.
        --   * RETURNING only produces a row if OUR insert won, so the "won"
        --     CTE is either our new claim or empty.
        --   * The UNION ALL branch reads the existing owner when we lost.
        -- If the competing claim commits while we wait on the conflict, this
        -- statement's snapshot may not see its row yet and both branches come
        -- back empty. The retry SELECT runs as a new statement and handles that race.
        WITH won AS (
            INSERT INTO cb_stream_keys AS k (stream_name, key, ref_kind, ref_id)
            VALUES (cb_stream_publish.stream,
                    cb_stream_publish.key,
                    CASE WHEN _future THEN 'pending' ELSE 'message' END::cb_ref_kind, _id)
            ON CONFLICT (stream_name, key)
            DO UPDATE SET ref_id = k.ref_id WHERE FALSE
            RETURNING k.ref_kind, k.ref_id
        )
        SELECT ref.ref_kind, ref.ref_id INTO ref_kind, ref_id FROM (
            SELECT w.ref_kind, w.ref_id FROM won w
            UNION ALL
            SELECT k.ref_kind, k.ref_id FROM cb_stream_keys k
            WHERE k.stream_name = cb_stream_publish.stream
              AND k.key         = cb_stream_publish.key
            LIMIT 1
        ) ref;
        -- Handle race edge case.
        IF ref_id IS NULL THEN
            SELECT k.ref_kind, k.ref_id INTO ref_kind, ref_id
            FROM cb_stream_keys k
            WHERE k.stream_name = cb_stream_publish.stream
              AND k.key         = cb_stream_publish.key;
        END IF;

        -- It's a duplicate. Return the existing id.
        IF ref_id <> _id THEN
            existing := true;
            RETURN;
        END IF;
    END IF;

    ---- Delayed delivery: store as pending, notify the sweeper and return early. ----
    IF _future THEN
        ref_kind := 'pending';
        ref_id   := coalesce(_id, nextval(pg_get_serial_sequence('cb_stream_pending', 'id')));

        INSERT INTO cb_stream_pending
            (id, stream_name, topic, payload, headers, deliver_at, key)
        VALUES (
            ref_id,
            cb_stream_publish.stream,
            cb_stream_publish.topic,
            cb_stream_publish.payload,
            cb_stream_publish.headers,
            _deliver_at,
            cb_stream_publish.key
        );

        -- Notify the sweeper.
        PERFORM pg_notify(current_schema || '.cb_pending',
            to_char(_deliver_at AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.US"Z"'));

        RETURN;
    END IF;

    ---- Immediate delivery: store as message, notify the assigner. ----
    ref_kind := 'message';
    ref_id   := coalesce(_id, nextval(pg_get_serial_sequence('cb_stream_messages', 'id')));

    -- id is GENERATED BY DEFAULT, so explicit inserts are allowed.
    INSERT INTO cb_stream_messages (id, stream_name, topic, payload, headers)
    VALUES (
        ref_id,
        cb_stream_publish.stream,
        cb_stream_publish.topic,
        cb_stream_publish.payload,
        cb_stream_publish.headers
    );

    -- Notify the position assigner.
    PERFORM pg_notify(current_schema || '.cb_s_' || cb_stream_publish.stream, cb_stream_publish.topic);
END;
$$;
-- +goose statementend

-- +goose statementbegin
CREATE FUNCTION _cb_stream_assign_positions(stream text, batch int DEFAULT 5000)
RETURNS int   -- rows assigned; 0 = caught up, or lost the election
LANGUAGE plpgsql AS $$
DECLARE
    _n int;
BEGIN
    -- Only one process may number a stream at a time.
    IF NOT pg_try_advisory_xact_lock(hashtext('cb_assign:' || _cb_stream_assign_positions.stream)) THEN
        RETURN 0;
    END IF;

    WITH unassigned AS (
        SELECT m.id, row_number() OVER (ORDER BY m.id) AS pos
        FROM cb_stream_messages m
        WHERE m.stream_name = _cb_stream_assign_positions.stream AND m.position IS NULL
        ORDER BY m.id
        LIMIT _cb_stream_assign_positions.batch
    ), bump AS (
        UPDATE cb_streams s
        SET last_position = s.last_position + (SELECT count(*) FROM unassigned)
        WHERE s.name = _cb_stream_assign_positions.stream
        RETURNING s.last_position - (SELECT count(*) FROM unassigned) AS last_pos
    ), assigned AS (
        UPDATE cb_stream_messages m
        SET position = bump.last_pos + unassigned.pos
        FROM unassigned, bump
        WHERE m.stream_name = _cb_stream_assign_positions.stream
          AND m.id = unassigned.id
          AND m.position IS NULL -- Just to be sure.
        RETURNING 1
    )
    SELECT count(*) INTO _n FROM assigned;

    IF _n > 0 THEN
        -- Inform consumers that new messages are available.
        PERFORM pg_notify(current_schema || '.cb_s_' || _cb_stream_assign_positions.stream, '');
    END IF;
    RETURN _n;
END;
$$;
-- +goose statementend

-- +goose statementbegin
CREATE FUNCTION cb_stream_read(stream text, cursor text, max_count int DEFAULT 100)
RETURNS SETOF cb_stream_messages
LANGUAGE plpgsql AS $$
DECLARE
    _pos bigint;
    _last_pos bigint;
    _new_pos bigint;
BEGIN
    -- one reader per cursor: a competing reader blocks here, not double-reads
    SELECT c.position INTO _pos FROM cb_stream_cursors c
    WHERE c.stream_name = cb_stream_read.stream AND c.name = cb_stream_read.cursor
    FOR UPDATE;
    IF NOT FOUND THEN
        RAISE EXCEPTION 'catbird: cursor %.% not defined', cb_stream_read.stream, cb_stream_read.cursor;
    END IF;
    SELECT s.last_position INTO _last_pos FROM cb_streams s
    WHERE s.name = cb_stream_read.stream;

    -- where this batch ends (NULL = caught up)
    SELECT max(b.position) INTO _new_pos FROM (
        SELECT m.position FROM cb_stream_messages m
        WHERE m.stream_name = cb_stream_read.stream
          AND m.position > _pos AND m.position <= _last_pos
        ORDER BY m.position LIMIT max_count) b;
    IF _new_pos IS NULL THEN RETURN; END IF;

    -- emit the batch, then keep going — the one place RETURN QUERY's
    -- "append and continue" behavior is what we want
    RETURN QUERY
    SELECT m.* FROM cb_stream_messages m
    WHERE m.stream_name = cb_stream_read.stream
      AND m.position > _pos AND m.position <= _new_pos
    ORDER BY m.position;

    UPDATE cb_stream_cursors c SET position = _new_pos
    WHERE c.stream_name = cb_stream_read.stream AND c.name = cb_stream_read.cursor;
END; $$;
-- +goose statementend

-- +goose down

DROP FUNCTION cb_stream_publish(text, text, jsonb, jsonb, text, interval, timestamptz);
DROP FUNCTION cb_stream_ensure(text);
DROP FUNCTION _cb_stream_assign_positions(text, int);
DROP FUNCTION _cb_valid_stream_name(text);
DROP FUNCTION cb_valid_name(text);
DROP TABLE cb_stream_messages;
DROP TABLE cb_stream_cursors;
DROP TABLE cb_stream_keys;
DROP TABLE cb_stream_pending;
DROP TABLE cb_streams;
DROP TYPE cb_ref_kind;
