-- +goose up

CREATE TYPE cb_ref_kind AS ENUM ('message', 'pending');

-- +goose statementbegin
CREATE FUNCTION cb_valid_name(name text)
RETURNS boolean
LANGUAGE sql IMMUTABLE AS $$
    SELECT name IS NOT NULL
       AND name !~ '__'   -- '__' is reserved, it encodes dots in partition names
       AND name ~ '^[a-z][a-z0-9_]*$'
       AND octet_length(name) <= 20
$$;
-- +goose statementend

-- +goose statementbegin
CREATE FUNCTION _cb_valid_stream_name(name text)
RETURNS boolean
LANGUAGE sql IMMUTABLE AS $$
    SELECT name IS NOT NULL
       AND name ~ '^[a-z][a-z0-9_]*(\.[a-z][a-z0-9_]*){0,2}$'
       AND octet_length(name) <= 44
$$;
-- +goose statementend

-- +goose statementbegin
CREATE FUNCTION _cb_stream_notify(stream text, payload text)
RETURNS void LANGUAGE sql AS $$
    SELECT pg_notify(current_schema || '.cbs_' || stream, payload);
$$;
-- +goose statementend

CREATE TABLE cb_streams (
    name text PRIMARY KEY CHECK (_cb_valid_stream_name(name)),
    last_position bigint NOT NULL DEFAULT 0
);

CREATE TABLE cb_stream_cursors (
    stream_name text NOT NULL REFERENCES cb_streams(name) ON DELETE CASCADE,
    name text NOT NULL CHECK (cb_valid_name(name)), -- single segment: dots are streams-only
    position bigint NOT NULL DEFAULT 0, -- how far this cursor has read: everything at or below this position is acked
    PRIMARY KEY (stream_name, name)
);

-- Messages that are delayed. _cb_stream_deliver_pending moves them
-- into cb_stream_messages when they are due.
CREATE TABLE cb_stream_pending (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    stream_name text NOT NULL REFERENCES cb_streams(name) ON DELETE CASCADE,
    topic text,
    payload jsonb NOT NULL,
    headers jsonb NOT NULL DEFAULT '{}' CHECK (jsonb_typeof(headers) = 'object'),
    deliver_at timestamptz NOT NULL,
    key text -- set when delayed message has a deduplication key
);

CREATE INDEX ON cb_stream_pending (deliver_at);

CREATE TABLE cb_stream_keys (
    stream_name text NOT NULL REFERENCES cb_streams(name) ON DELETE CASCADE,
    key         text NOT NULL,
    ref_kind    cb_ref_kind NOT NULL,
    ref_id      bigint NOT NULL,
    created_at  timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (stream_name, key)
);

CREATE INDEX ON cb_stream_keys (stream_name, created_at);

-- No identity column: identity on partitioned tables needs Postgres 17, and
-- the floor is 14 (plan D16). Explicit sequence instead; OWNED BY keeps
-- pg_get_serial_sequence() working in cb_stream_publish.
CREATE SEQUENCE cb_stream_messages_id_seq;

CREATE TABLE cb_stream_messages (
    id bigint NOT NULL DEFAULT nextval('cb_stream_messages_id_seq'),
    stream_name text NOT NULL REFERENCES cb_streams(name) ON DELETE CASCADE,
    position bigint,
    topic text,
    payload jsonb NOT NULL,
    headers jsonb NOT NULL DEFAULT '{}' CHECK (jsonb_typeof(headers) = 'object'),
    created_at timestamptz NOT NULL DEFAULT now()
)
PARTITION BY LIST (stream_name);

ALTER SEQUENCE cb_stream_messages_id_seq OWNED BY cb_stream_messages.id;

CREATE INDEX ON cb_stream_messages (stream_name, position);

CREATE TABLE cb_stream_queues (
    stream_name text NOT NULL REFERENCES cb_streams(name) ON DELETE CASCADE,
    name text NOT NULL CHECK (cb_valid_name(name)),
    claimed_position bigint NOT NULL DEFAULT 0, -- everything at or below this position is claimed
    closed_position bigint NOT NULL DEFAULT 0, -- everything at or below this position is claimed and closed
    claim_ttl interval NOT NULL DEFAULT '30 seconds',
    PRIMARY KEY (stream_name, name),
    CHECK (closed_position <= claimed_position)
);

CREATE TABLE cb_stream_claims (
    stream_name text NOT NULL,
    queue_name text NOT NULL,
    from_position bigint NOT NULL,
    to_position bigint NOT NULL,
    consumer text NOT NULL,
    closed boolean NOT NULL DEFAULT false,
    ttl interval NOT NULL,
    expires_at timestamptz NOT NULL, -- past this moment any consumer may claim again
    created_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (stream_name, queue_name, from_position),
    FOREIGN KEY (stream_name, queue_name)
        REFERENCES cb_stream_queues(stream_name, name) ON DELETE CASCADE,
    CHECK (from_position <= to_position)
);

-- +goose statementbegin
CREATE FUNCTION cb_stream_ensure(stream text)
RETURNS void LANGUAGE plpgsql AS $$
BEGIN
    IF NOT cb_valid_name(cb_stream_ensure.stream) THEN
        RAISE EXCEPTION 'catbird: invalid stream name %; use [a-z][a-z0-9_]*, max 20 bytes', cb_stream_ensure.stream;
    END IF;
    PERFORM pg_advisory_xact_lock(hashtext('cb_stream_ensure'));
    INSERT INTO cb_streams (name) VALUES (cb_stream_ensure.stream) ON CONFLICT DO NOTHING;
    EXECUTE format(
        'CREATE TABLE IF NOT EXISTS %I PARTITION OF cb_stream_messages
         FOR VALUES IN (%L) PARTITION BY RANGE (created_at)',
        'cbm__' || cb_stream_ensure.stream, cb_stream_ensure.stream);
    EXECUTE format( -- TODO temporary
        'CREATE TABLE IF NOT EXISTS %I PARTITION OF %I
         FOR VALUES FROM (%L) TO (%L)',
        format('cbm__%s__dev', cb_stream_ensure.stream),
        'cbm__' || cb_stream_ensure.stream, '2000-01-01', '2100-01-01');
END; $$;
-- +goose statementend

-- +goose statementbegin
CREATE FUNCTION cb_stream_ensure_cursor(stream text, cursor text, start_position bigint DEFAULT NULL)
RETURNS void LANGUAGE plpgsql AS $$
DECLARE
    _start bigint;
BEGIN
    IF NOT cb_valid_name(cb_stream_ensure_cursor.cursor) THEN
        RAISE EXCEPTION 'catbird: invalid cursor name %; use [a-z][a-z0-9_]*, max 20 bytes',
            cb_stream_ensure_cursor.cursor;
    END IF;

    -- NULL start = tail: skip everything already in the stream.
    SELECT coalesce(cb_stream_ensure_cursor.start_position, s.last_position)
    INTO _start FROM cb_streams s WHERE s.name = cb_stream_ensure_cursor.stream;
    IF NOT FOUND THEN
        RAISE EXCEPTION 'catbird: stream % not defined', cb_stream_ensure_cursor.stream;
    END IF;

    INSERT INTO cb_stream_cursors (stream_name, name, position)
    VALUES (cb_stream_ensure_cursor.stream, cb_stream_ensure_cursor.cursor, _start)
    ON CONFLICT (stream_name, name) DO NOTHING;
END; $$;
-- +goose statementend

-- +goose statementbegin
CREATE FUNCTION cb_stream_ensure_queue(stream text, queue text, start_position bigint DEFAULT NULL)
RETURNS void LANGUAGE plpgsql AS $$
DECLARE
    _start bigint;
BEGIN
    IF NOT cb_valid_name(cb_stream_ensure_queue.queue) THEN
        RAISE EXCEPTION 'catbird: invalid queue name %; use [a-z][a-z0-9_]*, max 20 bytes',
            cb_stream_ensure_queue.queue;
    END IF;

    SELECT coalesce(cb_stream_ensure_queue.start_position, s.last_position)
    INTO _start FROM cb_streams s WHERE s.name = cb_stream_ensure_queue.stream;
    IF NOT FOUND THEN
        RAISE EXCEPTION 'catbird: stream % not defined', cb_stream_ensure_queue.stream;
    END IF;

    INSERT INTO cb_stream_queues (stream_name, name, claimed_position, closed_position)
    VALUES (cb_stream_ensure_queue.stream, cb_stream_ensure_queue.queue, _start, _start)
    ON CONFLICT (stream_name, name) DO NOTHING;
END; $$;
-- +goose statementend

-- +goose statementbegin
CREATE FUNCTION cb_stream_publish(
    stream     text,
    topic      text,
    payload    jsonb,
    headers    jsonb       DEFAULT '{}',
    key        text        DEFAULT NULL, -- deduplication key (keep oldest)
    delay      interval    DEFAULT NULL, -- relative delayed delivery
    deliver_at timestamptz DEFAULT NULL, -- absolute delayed delivery

    OUT ref_kind cb_ref_kind,
    OUT ref_id   bigint,
    OUT existing boolean -- true: key already taken, nothing stored
)
LANGUAGE plpgsql AS $$
-- Resolve ambiguous names to COLUMNS inside SQL statements: the parameter
-- `key` collides with cb_stream_keys.key in the ON CONFLICT target, which
-- cannot be table-qualified. Safe because parameters are always referenced
-- qualified (cb_stream_publish.key) in this body.
#variable_conflict use_column
DECLARE
    _id bigint;
    _deliver_at timestamptz;
    _future boolean;
BEGIN
    existing := false;

    -- Validate arguments.
    IF delay IS NOT NULL AND cb_stream_publish.deliver_at IS NOT NULL THEN
        RAISE EXCEPTION 'catbird: cannot specify both delay and deliver_at';
    END IF;

    _deliver_at := coalesce(cb_stream_publish.deliver_at, clock_timestamp() + cb_stream_publish.delay);
    _future := _deliver_at IS NOT NULL AND _deliver_at > clock_timestamp();

    -- Check the stream exists.
    PERFORM 1 FROM cb_streams s WHERE s.name = cb_stream_publish.stream;
    IF NOT FOUND THEN
        RAISE EXCEPTION 'catbird: stream % not defined', cb_stream_publish.stream;
    END IF;

    ---- Deduplication by key. ----
    IF cb_stream_publish.key IS NOT NULL THEN
        _id := CASE WHEN _future
            THEN nextval(pg_get_serial_sequence('cb_stream_pending', 'id'))
            ELSE nextval(pg_get_serial_sequence('cb_stream_messages', 'id')) END;

        -- Try to claim this key. If the key is already claimed, learn who owns it.
        -- Do not simplify:
        --   * ON CONFLICT ... DO UPDATE ... WHERE FALSE: on a duplicate key we
        --     must NOT modify the existing row, but plain DO NOTHING would
        --     neither lock it nor let us RETURN it. DO UPDATE locks the
        --     existing row; WHERE FALSE then cancels the update itself.
        --   * RETURNING only produces a row if OUR insert won, so the "won"
        --     CTE is either our new claim or empty.
        --   * The UNION ALL branch reads the existing owner when we lost.
        -- If the competing claim commits while we wait on the conflict, this
        -- statement's snapshot may not see its row yet and both branches come
        -- back empty. The retry SELECT runs as a new statement and handles that race.
        WITH won AS (
            INSERT INTO cb_stream_keys AS k (stream_name, key, ref_kind, ref_id)
            VALUES (cb_stream_publish.stream,
                    cb_stream_publish.key,
                    CASE WHEN _future THEN 'pending' ELSE 'message' END::cb_ref_kind, _id)
            ON CONFLICT (stream_name, key)
            DO UPDATE SET ref_id = k.ref_id WHERE FALSE
            RETURNING k.ref_kind, k.ref_id
        )
        SELECT ref.ref_kind, ref.ref_id INTO ref_kind, ref_id FROM (
            SELECT w.ref_kind, w.ref_id FROM won w
            UNION ALL
            SELECT k.ref_kind, k.ref_id FROM cb_stream_keys k
            WHERE k.stream_name = cb_stream_publish.stream
              AND k.key         = cb_stream_publish.key
            LIMIT 1
        ) ref;
        -- Handle race edge case.
        IF ref_id IS NULL THEN
            SELECT k.ref_kind, k.ref_id INTO ref_kind, ref_id
            FROM cb_stream_keys k
            WHERE k.stream_name = cb_stream_publish.stream
              AND k.key         = cb_stream_publish.key;
        END IF;

        -- It's a duplicate. Return the existing id.
        IF ref_id <> _id THEN
            existing := true;
            RETURN;
        END IF;
    END IF;

    ---- Delayed delivery: store as pending, notify the sweeper and return early. ----
    IF _future THEN
        ref_kind := 'pending';
        ref_id   := coalesce(_id, nextval(pg_get_serial_sequence('cb_stream_pending', 'id')));

        INSERT INTO cb_stream_pending
            (id, stream_name, topic, payload, headers, deliver_at, key)
        VALUES (
            ref_id,
            cb_stream_publish.stream,
            cb_stream_publish.topic,
            cb_stream_publish.payload,
            cb_stream_publish.headers,
            _deliver_at,
            cb_stream_publish.key
        );

        PERFORM pg_notify(current_schema || '.cb_pending',
            to_char(_deliver_at AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.US"Z"'));

        RETURN;
    END IF;

    ---- Immediate delivery: store as message, notify the assigner. ----
    ref_kind := 'message';
    ref_id   := coalesce(_id, nextval(pg_get_serial_sequence('cb_stream_messages', 'id')));

    -- id is GENERATED BY DEFAULT, so explicit inserts are allowed.
    INSERT INTO cb_stream_messages (id, stream_name, topic, payload, headers)
    VALUES (
        ref_id,
        cb_stream_publish.stream,
        cb_stream_publish.topic,
        cb_stream_publish.payload,
        cb_stream_publish.headers
    );

    -- Notify the position assigner.
    PERFORM _cb_stream_notify(cb_stream_publish.stream, cb_stream_publish.topic);
END;
$$;
-- +goose statementend

-- +goose statementbegin
CREATE FUNCTION _cb_stream_assign_positions(stream text, batch_size int DEFAULT 5000)
RETURNS int
LANGUAGE plpgsql AS $$
DECLARE
    _n int;
BEGIN
    -- Only one process may number a stream at a time.
    IF NOT pg_try_advisory_xact_lock(hashtext('cb_assign:' || _cb_stream_assign_positions.stream)) THEN
        RETURN 0;
    END IF;

    WITH unassigned AS (
        SELECT m.id, row_number() OVER (ORDER BY m.id) AS pos
        FROM cb_stream_messages m
        WHERE m.stream_name = _cb_stream_assign_positions.stream AND m.position IS NULL
        ORDER BY m.id
        LIMIT _cb_stream_assign_positions.batch_size
    ), bump AS (
        UPDATE cb_streams s
        SET last_position = s.last_position + (SELECT count(*) FROM unassigned)
        WHERE s.name = _cb_stream_assign_positions.stream
        RETURNING s.last_position - (SELECT count(*) FROM unassigned) AS last_pos
    ), assigned AS (
        UPDATE cb_stream_messages m
        SET position = bump.last_pos + unassigned.pos
        FROM unassigned, bump
        WHERE m.stream_name = _cb_stream_assign_positions.stream
          AND m.id = unassigned.id
           -- Not really needed with the advisory lock, just extra safety.
           -- Without the lock, gaps would appear in the position sequence,
           -- but no existing message would be updated.
          AND m.position IS NULL
        RETURNING 1
    )
    SELECT count(*) INTO _n FROM assigned;

    IF _n > 0 THEN
        -- Inform consumers that new messages are available.
        PERFORM _cb_stream_notify(_cb_stream_assign_positions.stream, '');
    END IF;
    RETURN _n;
END;
$$;
-- +goose statementend

-- +goose statementbegin
CREATE FUNCTION _cb_stream_deliver_pending(batch_size int DEFAULT 500)
RETURNS int LANGUAGE plpgsql AS $$
DECLARE
    _p cb_stream_pending;
    _msg_id bigint;
    _n int := 0;
BEGIN
    FOR _p IN
        SELECT * FROM cb_stream_pending
        WHERE deliver_at <= clock_timestamp()
        ORDER BY deliver_at LIMIT _cb_stream_deliver_pending.batch_size
        FOR UPDATE SKIP LOCKED
    LOOP
        DELETE FROM cb_stream_pending WHERE id = _p.id;

        -- Publish the message
        INSERT INTO cb_stream_messages (stream_name, topic, payload, headers)
        VALUES (_p.stream_name, _p.topic, _p.payload, _p.headers)
        RETURNING id INTO _msg_id;
        -- If the message has a key, update it.
        UPDATE cb_stream_keys k
        SET ref_kind = 'message', ref_id = _msg_id
        WHERE k.ref_kind = 'pending' AND k.ref_id = _p.id AND k.stream_name = _p.stream_name;

        PERFORM _cb_stream_notify(_p.stream_name, _p.topic);

        _n := _n + 1;
    END LOOP;
    RETURN _n;
END;
$$;
-- +goose statementend

-- +goose statementbegin
CREATE FUNCTION cb_stream_read(stream text, cursor text, batch_size int DEFAULT 100)
RETURNS SETOF cb_stream_messages
LANGUAGE plpgsql AS $$
DECLARE
    _pos bigint;
    _new_pos bigint;
BEGIN
    -- Get current cursor position.
    SELECT c.position INTO _pos FROM cb_stream_cursors c
    WHERE c.stream_name = cb_stream_read.stream AND c.name = cb_stream_read.cursor
    FOR UPDATE;

    IF NOT FOUND THEN
        RAISE EXCEPTION 'catbird: cursor %.% not defined', cb_stream_read.stream, cb_stream_read.cursor;
    END IF;

    SELECT max(b.position) INTO _new_pos FROM (
        SELECT m.position FROM cb_stream_messages m
        WHERE m.stream_name = cb_stream_read.stream
          AND m.position > _pos
        ORDER BY m.position
        LIMIT cb_stream_read.batch_size) b;

    IF _new_pos IS NULL THEN
        RETURN;
    END IF;

    RETURN QUERY
    SELECT m.* FROM cb_stream_messages m
    WHERE m.stream_name = cb_stream_read.stream
      AND m.position > _pos AND m.position <= _new_pos
    ORDER BY m.position;

    UPDATE cb_stream_cursors c SET position = _new_pos
    WHERE c.stream_name = cb_stream_read.stream AND c.name = cb_stream_read.cursor;
END; $$;
-- +goose statementend

-- +goose statementbegin
CREATE FUNCTION cb_stream_claim(
    stream     text,
    queue      text,
    consumer   text,
    batch_size int      DEFAULT 100,
    ttl        interval DEFAULT NULL, -- the queue's claim_ttl is used if NULL

    OUT from_position bigint, -- NULL when there is nothing to claim
    OUT to_position   bigint,
    OUT expires_at    timestamptz
)
LANGUAGE plpgsql AS $$
DECLARE
    _ttl interval;
    _claimed_pos bigint;
    _last_pos bigint;
BEGIN
    SELECT coalesce(cb_stream_claim.ttl, q.claim_ttl) INTO _ttl FROM cb_stream_queues q
    WHERE q.stream_name = cb_stream_claim.stream AND q.name = cb_stream_claim.queue;
    IF NOT FOUND THEN
        RAISE EXCEPTION 'catbird: queue %.% not defined', cb_stream_claim.stream, cb_stream_claim.queue;
    END IF;

    ---- Try to adopt an expired claim. ----
    UPDATE cb_stream_claims c
    SET consumer = cb_stream_claim.consumer,
        ttl = coalesce(cb_stream_claim.ttl, c.ttl),
        expires_at = clock_timestamp() + coalesce(cb_stream_claim.ttl, c.ttl)
    WHERE (c.stream_name, c.queue_name, c.from_position) = (
        SELECT r.stream_name, r.queue_name, r.from_position
        FROM cb_stream_claims r
        WHERE r.stream_name = cb_stream_claim.stream
          AND r.queue_name  = cb_stream_claim.queue
          AND NOT r.closed
          AND r.expires_at <= clock_timestamp()
        ORDER BY r.from_position
        LIMIT 1
        FOR UPDATE SKIP LOCKED)
    RETURNING c.from_position, c.to_position, c.expires_at
    INTO from_position, to_position, expires_at;
    IF FOUND THEN
        RETURN;
    END IF;

    ---- Claim a fresh range. ----
    SELECT q.claimed_position INTO _claimed_pos FROM cb_stream_queues q
    WHERE q.stream_name = cb_stream_claim.stream AND q.name = cb_stream_claim.queue
    FOR UPDATE;

    -- No lock needed on the streams row. last_position only grows,
    -- so a stale read just means a slightly smaller range.
    SELECT s.last_position INTO _last_pos FROM cb_streams s
    WHERE s.name = cb_stream_claim.stream;

    IF _claimed_pos >= _last_pos THEN
        RETURN; -- caught up, return NULLs
    END IF;

    from_position := _claimed_pos + 1;
    to_position := least(_claimed_pos + cb_stream_claim.batch_size, _last_pos);
    expires_at := clock_timestamp() + _ttl;

    UPDATE cb_stream_queues q SET claimed_position = cb_stream_claim.to_position
    WHERE q.stream_name = cb_stream_claim.stream AND q.name = cb_stream_claim.queue;

    INSERT INTO cb_stream_claims
        (stream_name, queue_name, from_position, to_position, consumer, ttl, expires_at)
    VALUES (cb_stream_claim.stream, cb_stream_claim.queue,
        cb_stream_claim.from_position, cb_stream_claim.to_position,
        cb_stream_claim.consumer, _ttl, cb_stream_claim.expires_at);
END;
$$;
-- +goose statementend

-- +goose statementbegin
-- If ttl is NULL, the claim's existing ttl is used. Returns the new expires_at timestamp.
CREATE FUNCTION cb_stream_extend_claim(
    stream text, queue text,
    consumer text,
    from_position bigint,
    ttl interval DEFAULT NULL
)
RETURNS timestamptz LANGUAGE plpgsql AS $$
DECLARE
    _expires_at timestamptz;
BEGIN
    IF cb_stream_extend_claim.ttl <= '0' THEN
        RAISE EXCEPTION 'catbird: invalid ttl %', cb_stream_extend_claim.ttl;
    END IF;

    UPDATE cb_stream_claims c
    SET expires_at = clock_timestamp() + coalesce(cb_stream_extend_claim.ttl, c.ttl)
    WHERE c.stream_name   = cb_stream_extend_claim.stream
      AND c.queue_name    = cb_stream_extend_claim.queue
      AND c.consumer      = cb_stream_extend_claim.consumer
      AND c.from_position = cb_stream_extend_claim.from_position
      AND NOT c.closed
    RETURNING c.expires_at INTO _expires_at;
    RETURN _expires_at;
END; $$;
-- +goose statementend

-- +goose statementbegin
-- the claim expires immediately, and the next cb_stream_claim call may adopt it.
CREATE FUNCTION cb_stream_release_claim(
    stream text,
    queue text,
    consumer text,
    from_position bigint
)
RETURNS void LANGUAGE plpgsql AS $$
BEGIN
    UPDATE cb_stream_claims c
    SET expires_at = clock_timestamp()
    WHERE c.stream_name   = cb_stream_release_claim.stream
      AND c.queue_name    = cb_stream_release_claim.queue
      AND c.consumer      = cb_stream_release_claim.consumer
      AND c.from_position = cb_stream_release_claim.from_position
      AND NOT c.closed;
END; $$;
-- +goose statementend

-- +goose statementbegin
CREATE FUNCTION cb_stream_close_claim(
    stream text,
    queue text,
    consumer text,
    from_position bigint
)
RETURNS void LANGUAGE plpgsql AS $$
DECLARE
    _closed_pos bigint;
    _to_pos bigint;
BEGIN
    -- Only the current owner may close.
    UPDATE cb_stream_claims c SET closed = true
    WHERE c.stream_name   = cb_stream_close_claim.stream
      AND c.queue_name    = cb_stream_close_claim.queue
      AND c.consumer      = cb_stream_close_claim.consumer
      AND c.from_position = cb_stream_close_claim.from_position
      AND NOT c.closed;
    IF NOT FOUND THEN
        RETURN;
    END IF;

    -- Move the closed position forward over adjacent closed claims until an
    -- open claim stops it. Delete every claim it passes, the table only
    -- holds work in progress.
    SELECT q.closed_position INTO _closed_pos FROM cb_stream_queues q
    WHERE q.stream_name = cb_stream_close_claim.stream AND q.name = cb_stream_close_claim.queue
    FOR UPDATE;

    LOOP
        DELETE FROM cb_stream_claims c
        WHERE c.stream_name   = cb_stream_close_claim.stream
          AND c.queue_name    = cb_stream_close_claim.queue
          AND c.from_position = _closed_pos + 1
          AND c.closed
        RETURNING c.to_position INTO _to_pos;
        EXIT WHEN NOT FOUND;
        _closed_pos := _to_pos;
    END LOOP;

    UPDATE cb_stream_queues q SET closed_position = _closed_pos
    WHERE q.stream_name = cb_stream_close_claim.stream AND q.name = cb_stream_close_claim.queue
      AND q.closed_position < _closed_pos;
END; $$;
-- +goose statementend

-- +goose down

DROP FUNCTION cb_stream_close_claim(text, text, text, bigint);
DROP FUNCTION cb_stream_release_claim(text, text, text, bigint);
DROP FUNCTION cb_stream_extend_claim(text, text, text, bigint, interval);
DROP FUNCTION cb_stream_claim(text, text, text, int, interval);
DROP FUNCTION cb_stream_ensure_queue(text, text, bigint);
DROP FUNCTION cb_stream_ensure_cursor(text, text, bigint);
DROP FUNCTION cb_stream_read(text, text, int);
DROP TABLE cb_stream_claims;
DROP TABLE cb_stream_queues;
DROP FUNCTION cb_stream_publish(text, text, jsonb, jsonb, text, interval, timestamptz);
DROP FUNCTION cb_stream_ensure(text);
DROP FUNCTION _cb_stream_deliver_pending(int);
DROP FUNCTION _cb_stream_assign_positions(text, int);
DROP FUNCTION _cb_stream_notify(text, text);
DROP TABLE cb_stream_messages;
DROP TABLE cb_stream_cursors;
DROP TABLE cb_stream_keys;
DROP TABLE cb_stream_pending;
DROP TABLE cb_streams;
DROP FUNCTION _cb_valid_stream_name(text);
DROP FUNCTION cb_valid_name(text);
DROP TYPE cb_ref_kind;
